package com.example

import org.mp4parser.Container
import org.mp4parser.boxes.apple.AppleCoverBox
import org.mp4parser.boxes.apple.AppleItemListBox
import org.mp4parser.boxes.iso14496.part12.MetaBox
import org.mp4parser.boxes.iso14496.part12.MovieBox
import org.mp4parser.boxes.iso14496.part12.UserDataBox
import org.mp4parser.boxes.iso14496.part12.HandlerBox
import org.mp4parser.muxer.Movie
import org.mp4parser.muxer.builder.DefaultMp4Builder
import org.mp4parser.muxer.container.mp4.MovieCreator
import java.io.File
import java.io.RandomAccessFile

object VideoProcessor {

    fun setCover(inputVideoPath: String, coverBytes: ByteArray, isJpg: Boolean, outputVideoPath: String) {
        val movie: Movie = MovieCreator.build(inputVideoPath)

        val builder = DefaultMp4Builder()
        val outContainer: Container = builder.build(movie)
        
        var moov: MovieBox? = null
        for (box in outContainer.boxes) {
            if (box is MovieBox) {
                moov = box
                break
            }
        }
        
        if (moov == null) {
            throw Exception("No moov box generated by builder.")
        }

        var udta: UserDataBox? = moov.getBoxes(UserDataBox::class.java).firstOrNull()
        if (udta == null) {
            udta = UserDataBox()
            moov.addBox(udta)
        }

        var meta: MetaBox? = udta.getBoxes(MetaBox::class.java).firstOrNull()
        if (meta == null) {
            meta = MetaBox()
            val hdlr = HandlerBox()
            hdlr.name = "Apple mark"
            hdlr.handlerType = "mdir"
            meta.addBox(hdlr)
            udta.addBox(meta)
        }

        var ilst: AppleItemListBox? = meta.getBoxes(AppleItemListBox::class.java).firstOrNull()
        if (ilst == null) {
            ilst = AppleItemListBox()
            meta.addBox(ilst)
        }

        // Remove existing cover if any
        val newBoxes = ArrayList<org.mp4parser.Box>()
        for (box in ilst.boxes) {
            if (box !is AppleCoverBox) {
                newBoxes.add(box)
            }
        }
        ilst.boxes = newBoxes

        val cover = AppleCoverBox()
        if (isJpg) {
            cover.setJpg(coverBytes)
        } else {
            cover.setPng(coverBytes)
        }
        ilst.addBox(cover)

        val pOut = File(outputVideoPath)
        if (pOut.exists()) {
            pOut.delete()
        }
        val outRac = RandomAccessFile(pOut, "rw")
        val fc = outRac.channel
        outContainer.writeContainer(fc)
        fc.close()
        outRac.close()
    }
}
